site_name: "JARPCdantic"
repo_url: https://github.com/whiteapfel/jarpcdantic

theme:
  name: "material"
  language: ru
#  custom_dir: 'docs/theme'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: "Dark Theme"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: "Light Theme"
  features:
    - content.tabs.link
    - content.code.annotate
    - announce.dismiss
    - navigation.tabs
nav:
- Overview: index.md
- Core Components:
  - Core Overview: core/index.md
  - Manager: core/manager.md
  - Dispatcher: core/dispatcher.md
  - Router: core/router.md
  - Client: core/client.md
- Transport:
  - Overview: transport/index.md
  - Pre-defined : transport/predefined.md
  - Cabbagok: transport/cabbagok.md
  - Custom: transport/custom.md


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 3
          show_root_heading: True
          parameter_headings: false
          show_source: False
          docstring_style: google
          show_if_no_docstring: false
          members_order: source
          docstring_section_style: table

##          show_symbol_type_heading: true
#          docstring_options:
#            ignore_init_summary: true

markdown_extensions:
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.extra
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
